#!/bin/bash
[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"

DIR="$(dirname "$(readlink -f "$0")")"
TITLE='MDK2 HD'
PREFIX='mdk2hd'
ARCHIVE='MDK2 HD*'
. $DIR/../base


POL_SetupWindow_Init
POL_Debug_Init
POL_SetupWindow_presentation "$TITLE" "Overhaul Games" "http://www.overhaulgames.com/mdk2hd/" "justin8" "$PREFIX"

POL_Wine_SelectPrefix "$PREFIX"
POL_Wine_PrefixCreate

Set_OS winxp

sandbox

POL_SetupWindow_InstallMethod "DOWNLOAD,LOCAL"
mkdir -p "$WINEPREFIX/drive_c/games"

if [ "$INSTALL_METHOD" = "LOCAL" ]
then
	POL_SetupWindow_browse "Please select the installation archive to install." "$TITLE installation"
elif [ "$INSTALL_METHOD" = "DOWNLOAD" ]
then
	APP_ANSWER="$full_archive"
fi

# Install from archive
POL_SetupWindow_wait "Installation in progress." "$TITLE installation"
rm -rf "$WINEPREFIX/drive_c/games/*"
extract "$full_archive" "$WINEPREFIX/drive_c/games/"
[[ $? != 0 ]] && POL_Debug_Fatal

# Install libraries
POL_Call POL_Install_dxfullsetup

POL_Shortcut "mdk2hd.exe" "$TITLE"

POL_SetupWindow_Close
exit
