#!/bin/bash
ARCHIVES="/abachi/Game Installers/Windows"
full_archive="$(find "$ARCHIVES" -maxdepth 1 -iname "$ARCHIVE"|head -1)"

function sandbox {
mkdir -p "$HOME/.PlayOnLinux/shared-files"
find $WINEPREFIX/drive_c/ -type l -exec sh -c 'rm "{}";ln -s "$HOME/.PlayOnLinux/shared-files/$(basename "{}")" "{}"' \;
rm -rf "$WINEPREFIX/drive_c/users/$USER/Application Data"
ln -s "$HOME/.PlayOnLinux/shared-files/Application Data" "$WINEPREFIX/drive_c/users/$USER/Application Data"
}

function extract {
ext=$(echo $1 | grep -Eo '\.[a-zA-Z]+$' | tr '[:upper:]' '[:lower:]')
case $ext in
	.exe)
		POL_Wine start /unix "$1"
		;;
	.rar)
		unrar x "$1" "$2"
		;;
	.tgz|.txz|.tlz)
		tar -C "$2" -xvf "$1"
		;;
	.zip)
		unzip "$1" -d "$2"
		;;
	*)
		echo "Unsupported archive format."
		exit 1
		;;
esac
}
